a = input("Digite algo:")
print("O tipo primitivo desse valor é",type(a))
print("Só tem espaços?",a.isspace())
print("É um número?",a.isnumeric())
print("É maisculo?",a.isupper())
print("É alphanumeric ?",a.isalpha())
print("É decimal ?",a.isdecimal())
print("Esta em minusculas",a.islower())
print("Esta capitalizada",a.istitle())